import { Client } from "@/types/client";
export const clientsData: Client[] = [
  {
    id: 1,
    title: "GrayGrids",
    logo: "/images/brands/brand-1.webp",
    logoWhite: "/images/brands/brand-1.webp",
    link: "https://graygrids.com/",
  },
  {
    id: 2,
    title: "Lineicons",
    logo: "/images/brands/brand-2.webp",
    logoWhite: "/images/brands/brand-2.webp",
    link: "https://lineicons.com/",
  },
  {
    id: 3,
    title: "Uideck",
    logo: "/images/brands/brand-3.webp",
    logoWhite: "/images/brands/brand-3.webp",
    link: "https://uideck.com/",
  },
  {
    id: 4,
    title: "AyroUI",
    logo: "/images/brands/brand-4.webp",
    logoWhite: "/images/brands/brand-4.webp",
    link: "https://ayroui.com/",
  },
  {
    id: 5,
    title: "TailGrids",
    logo: "/images/brands/brand-5.webp",
    logoWhite: "/images/brands/brand-5.webp",
    link: "https://tailgrids.com/",
  },
  {
    id: 6,
    title: "GrayGrids",
    logo: "/images/brands/brand-6.webp",
    logoWhite: "/images/brands/brand-6.webp",
    link: "https://graygrids.com/",
  },
  {
    id: 7,
    title: "Lineicons",
    logo: "/images/brands/brand-7.webp",
    logoWhite: "/images/brands/brand-7.webp",
    link: "https://lineicons.com/",
  },
  {
    id: 8,
    title: "Uideck",
    logo: "/images/brands/brand-8.webp",
    logoWhite: "/images/brands/brand-8.webp",
    link: "https://uideck.com/",
  },
  {
    id: 9,
    title: "AyroUI",
    logo: "/images/brands/brand-9.webp",
    logoWhite: "/images/brands/brand-9.webp",
    link: "https://ayroui.com/",
  },
  {
    id: 10,
    title: "TailGrids",
    logo: "/images/brands/brand-10.webp",
    logoWhite: "/images/brands/brand-10.webp",
    link: "https://tailgrids.com/",
  },
  {
    id: 11,
    title: "TailGrids",
    logo: "/images/brands/brand-11.webp",
    logoWhite: "/images/brands/brand-11.webp",
    link: "https://tailgrids.com/",
  },
  {
    id: 12,
    title: "GrayGrids",
    logo: "/images/brands/brand-12.webp",
    logoWhite: "/images/brands/brand-12.webp",
    link: "https://graygrids.com/",
  },
  {
    id: 13,
    title: "Lineicons",
    logo: "/images/brands/brand-13.webp",
    logoWhite: "/images/brands/brand-13.webp",
    link: "https://lineicons.com/",
  },
  {
    id: 14,
    title: "Uideck",
    logo: "/images/brands/brand-14.webp",
    logoWhite: "/images/brands/brand-14.webp",
    link: "https://uideck.com/",
  },
  {
    id: 15,
    title: "AyroUI",
    logo: "/images/brands/brand-15.webp",
    logoWhite: "/images/brands/brand-15.webp",
    link: "https://ayroui.com/",
  },
  // {
  //   id: 10,
  //   title: "TailGrids",
  //   logo: "/images/brands/tailgrids.svg",
  //   logoWhite: "/images/brands/tailgrids-white.svg",
  //   link: "https://tailgrids.com/",
  // },
];
